name: churn-prediction-vertex-ai
channels:
  - conda-forge
dependencies:
  - python==3.7
  - pip
  - matplotlib==3.2.2
  - numpy==1.21.6
  - pandas==1.3.5
  - seaborn==0.11.2
  - python-dateutil==2.8.2
  - spacy==3.4.2
  - pyyaml==6.0
  - pip:
    - google